import React from 'react'
import "./feature.css"
import feature1 from "../../assets/images/feature1.png";
import feature2 from "../../assets/images/feature2.png";
import feature3 from "../../assets/images/feature3.png";
const Feature = () => {
  return (
    <div className="feature">
        <div className="featureList">
          <div className="featureListWrapper">
            <div className="featureBox">
           <img src={feature1} className="featureImg" alt="" />
           <p className="featureTitle">Search</p>
           <p className="featureDescription">Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
            </div>
         <div className="featureBox">
         <img src={feature2} className="featureImg" alt="" />
           <p className="featureTitle">Select</p>
           <p className="featureDescription">Choose from thousands of options generated by the slogan maker that fit your needs.</p>
                
           </div>
        <div className="featureBox">
        <img src={feature3} className="featureImg" alt="" />
           <p className="featureTitle">Stand out</p>
           <p className="featureDescription3">Congrats on your new slogan. It's time to win the world!</p>
                
            </div>
            </div>
        </div>
    </div>
  )
}

export default Feature